apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: liiklus-scaledobject
  namespace: default
  labels:
    deploymentName: repeater-processor
spec:
  scaleTargetRef:
    deploymentName: repeater-processor
    containerName: processor
  pollingInterval: 5
  cooldownPeriod: 30
  triggers:
  - type: liiklus
    metadata:
      address: liiklus.default.svc.cluster.local:6565
      group: repeater
      topic: words
      lagThreshold: "5"
#  - type: liiklus
#    metadata:
#      address: liiklus.default.svc.cluster.local:6565
#      group: repeater
#      topic: words
#      lagThreshold: "7"
